execution_engine: asyncio
logger:
  transports: [console]  # You can use [file, console] for both
  level: debug
  path: "logs/mcp-agent.jsonl"  # Used for file transport
  # For dynamic log filenames:
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp"  # Or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
      
    filesystem:
      command: "npx"
      args:
        [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "./output/",
          "./policies/",
        ]
  

anthropic:
  default_model: "claude-3-5-haiku-20241022"